_BASE_: kmax_r50_tf.yaml
MODEL:
  # backbone part.
  BACKBONE:
    NAME: "D2ConvNeXtV2"
  WEIGHTS: "./convnextv2_huge_22k_512_ema.pkl"
  CONVNEXT:
    IN_CHANNELS: 3
    DEPTHS: [3, 3, 27, 3]
    DIMS: [352, 704, 1408, 2816]
    DROP_PATH_RATE: 0.3  # TDB
    OUT_INDICES: [0, 1, 2, 3]
  KMAX_DEEPLAB:
    SAVE_VIS_NUM: 100
SOLVER:
  IMS_PER_BATCH: 8